Скелет
serjyuriev/yandex-diploma-2 pull request #1
Opened 2022-07-21 19:11 UTC by serjyuriev

2022-08-07 22:25 UTC, rktkov requested changes

2022-08-07 22:25 UTC, rktkov commented on internal/app/repository/repository.go
> +	r.logger.Debug().Str("user", user.Login).Msg("marshalling user's info to bson")
Здесь и в других методах, реализующих интерфейс, надо строже подходить к проверке входных аргументов. Т.к. интерфейс общедоступный, пользоваться им может в общем смысле кто угодно, поэтому и на вход может поступить любое возможное значение, предусмотренное сигнатурой. Например, с user = nil, что явно приведет к панике в коде метода.

2022-08-07 22:25 UTC, rktkov commented on internal/app/repository/repository.go
> +	r.logger.Debug().Str("user", login).Msg("preparing filter")
Судя по сигнатуре метода, логин пользователя является уникальным идентификатором, но это никак не проверяется в методе записи нового пользователя в хранилище выше. Если мне не изменяет память, в монге уникальным идентификатором является внутреннее поле _id, а все остальные вполне могут дублироваться, что означает что ограничивающую логику надо реализовывать в пользовательском коде.

2022-08-07 22:25 UTC, rktkov commented on internal/app/repository/repository.go
> +	r.logger.Debug().Str("user", uuid.String()).Msg("preparing filter")
См. комментарий выше.

2022-08-07 22:25 UTC, rktkov commented on internal/app/service/service.go
> +	dbUser, err := s.repo.ReadUserByLogin(ctx, user.Login)
Вот этот бы код перенести в репозиторий, чтобы проверка на уникальность была в месте добавления данных в хранилище.

2022-08-07 22:25 UTC, rktkov commented on internal/app/handlers/handlers.go
> +				Password: item.Password,
Может стоит как-то защитить это поле. Уж очень страшно выглядит хранение его без шифрования.

2022-08-07 22:25 UTC, rktkov commented on internal/app/handlers/handlers.go
> +				CardSecurityCode: int32(item.CardSecurityCode),
См. комментарий выше "про страх".

2022-08-08 17:20 UTC, serjyuriev commented on internal/app/repository/repository.go
> +	r.logger.Debug().Str("user", user.Login).Msg("marshalling user's info to bson")
Добавил проверки для входных аргументов.

2022-08-08 17:20 UTC, serjyuriev commented on internal/app/repository/repository.go
> +	r.logger.Debug().Str("user", login).Msg("preparing filter")
Перенес проверку из сервисного пакета в репозиторий.

2022-08-08 17:20 UTC, serjyuriev commented on internal/app/handlers/handlers.go
> +				Password: item.Password,
Добавил шифрование.

2022-08-11 19:04 UTC, rktkov approved these changes

2022-08-13 10:19 UTC, merged